# -*- coding: utf-8 -*-
"""gsmap_phd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qP20A4gYdo66fWDr3DZ5nOjuyGpmWcrB
"""

!earthengine authenticate

import ee
import pandas as pd
import numpy as np
import time
import os
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

ee.Authenticate()
ee.Initialize(project='ee-adrhuertach')

region = ee.Geometry.Rectangle([-85, -60, -30, 15])
years = range(1998, 2025)

for year in years:
  # folder
  folder_path = "gsmap-" + str(year)
  os.makedirs("/content/drive/MyDrive/" + folder_path, exist_ok=True)

  year_days = pd.date_range(start=str(year) + "-01-01", end=str(year) + "-12-31", freq="D")
  for day in year_days:
    print(day)
    # date
    date = day.strftime("%Y-%m-%d")
    # data
    data_gpm = ee.ImageCollection('JAXA/GPM_L3/GSMaP/v8/operational').select("hourlyPrecipRate")
    data_gpm = data_gpm.filterDate(date)
    data_gpm = (data_gpm.sum()).clip(region)

    task_config = {
    'scale': 11132,
    'folder' : folder_path,
    'maxPixels' : 5265012984,
    }

    task = ee.batch.Export.image(data_gpm.toDouble(), date, task_config)
    task.start()
    time.sleep(1.25)







data_gpm = ee.ImageCollection('NASA/GPM_L3/IMERG_V07').select("precipitationUncal")

data_gpm = data_gpm.filterDate("2024-11-01")
data_gpm = (data_gpm.sum())

task_config = {
    'scale': 11132,
    'maxPixels' : 5265012984,
    }

task = ee.batch.Export.image(data_gpm.toDouble(), "gpm20241101", task_config)
task.start()

data_gsmap = ee.ImageCollection('JAXA/GPM_L3/GSMaP/v8/operational').select("hourlyPrecipRate")

data_gsmap = data_gsmap.filterDate("2024-11-01")
data_gsmap = (data_gsmap.sum())

task_config = {
    'scale': 11132,
    'maxPixels' : 5265012984,
    }

task = ee.batch.Export.image(data_gsmap.toDouble(), "gsmap20241101", task_config)
task.start()

